### ISSUE TITLE
add clarification to the documentation

### ISSUE THREAD

**Issue by vshagur** [chrisjm/openbrewerydb-gatsby#18]
# Feature request

## Overview

The [documentation page](https://www.openbrewerydb.org/documentation/04-autocomplete) does not indicate that the maximum number of breweries displayed is limited to 15.

## Include:

Please add this update.

## Tasks

- [ ] Task 1
- [ ] Task 2
- [ ] Task 3

## Screenshots & Diagrams

Add any screenshots or diagrams here to help with implementation.

## Additional context

Add any other context.

## Implementation notes

This section will be used by the assigned developer for any additional notes.

**Comment by chrisjm** [comment]
Fixed by #32
