### ISSUE TITLE
Support CORS

### ISSUE THREAD

**Issue by cfjedimaster** [chrisjm/openbrewerydb-gatsby#26]
# Feature request

Support CORS

## Overview

So that web applications can make use of the API.

**Comment by cfjedimaster** [comment]
Ugh sorry - really dumb error on my part.

**Comment by chrisjm** [comment]
Thanks @cfjedimaster! Anything I can do on my end to help out with this issue in the future? Any documentation updates that would have been helpful?

**Comment by cfjedimaster** [comment]
When I say it was dumb - it was really dumb. I copied the URL of the doc page into my code and not the *API* URL. The docs were just fine. :)
